FROM php:8.1.4-fpm-alpine3.15
COPY ./build/*.sh  /home/build/
RUN chmod +x /home/build/*.sh \
    && /home/build/package.sh  \
    && /home/build/variate.sh  \
    && /home/build/install-ext-base.sh  \
    && docker-php-source delete \
    && rm -rf /var/cache/*      \
    && rm -rf /tmp/*            \
    && rm -rf /home/*     \
    && php -m
